# Generated by Django 2.2.9 on 2020-01-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.IntegerField()),
                ('RequestDate', models.DateTimeField(auto_now_add=True)),
                ('CFApiUserId', models.CharField(max_length=100)),
                ('CFApiPassword', models.CharField(max_length=100)),
                ('IsTestLead', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='requestHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanapplication', to='homechallenge.RequestHeader'),
        ),
    ]
