# Generated by Django 2.2.9 on 2020-01-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge', '0002_auto_20200123_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='requestHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestHeader', to='homechallenge.RequestHeader'),
        ),
    ]
