# Generated by Django 2.2.9 on 2020-01-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge', '0004_remove_loanapplication_requestheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestheader',
            name='loanapplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homechallenge.LoanApplication'),
        ),
    ]
