# Generated by Django 2.2.9 on 2020-01-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge', '0007_homeaddressmodel_ownersmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeaddressmodel',
            old_name='owners',
            new_name='owner',
        ),
    ]
