# Generated by Django 2.2.9 on 2020-01-24 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge', '0009_selfreportedcashflowmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFApplicationDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.CharField(max_length=100)),
                ('StatedCreditHistory', models.IntegerField()),
                ('LegalEntityType', models.CharField(max_length=100)),
                ('FilterID', models.CharField(max_length=100)),
                ('loanapplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homechallenge.LoanApplication')),
            ],
        ),
    ]
