# Generated by Django 2.2.9 on 2020-01-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge', '0010_cfapplicationdatamodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestHeader',
            new_name='RequestHeaderModel',
        ),
    ]
