# Generated by Django 2.2.9 on 2020-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechallenge', '0011_auto_20200124_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownersmodel',
            name='PercentageOfOwnership',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requestheadermodel',
            name='CFRequestId',
            field=models.CharField(max_length=100),
        ),
    ]
